import LocalFontLoader from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Freedom Dance",
    description: "Generated by Shovit Dutta",
};
const Kurale = LocalFontLoader({ variable: "--font-Kurale", src: "./fonts/Kurale.ttf" });
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${Kurale.variable} antialiased font-Kurale`}>{children}</body>
        </html>
    );
}
